### ISSUE TITLE
[set-save-dir] problem and additional changes to be made.

### ISSUE THREAD

**Issue by neilhkim** [neilhkim/PIPpolarize#2]
# Problem:

- Reset asks the user to select save directory, even if the user did before pressing Reset.

# Changes to make:

- Change default N-runs from 9 to 1.
- add "save-xL-xS?" button
- add code saving xL-xS when run-index reaches N-runs.

**Comment by neilhkim** [comment]
when hitting "reset", if save-dir-name is empty & it is set to save result files, then prompt user-file windows.
+ if there is no need to save anything when hitting "reset", then change save-dir-name to "".

**Comment by neilhkim** [comment]
Add successful-reset-flag

If reset ends without meeting "stop"
set successsful-reset-flag true

at the beginning of "go" function,
if successful-reset-flag is false, stop

**Comment by neilhkim** [comment]
Relocate the function "initialize-saving" in the code.

**Comment by neilhkim** [comment]
Make it so that when saving (exporting) iface and view, it saves to the save-dir-name.

**Comment by neilhkim** [comment]
branch, 
update PIPpolarize.nlogo -> add button to auto-save xL-xS. -> add routine to auto-save xL-xS.
commit, push,
see if the remote got updated or not.

**Comment by svrajesh** [comment]
Neil has resolved this issue
